CREATE TABLE [dbo].[Parcels] (
    [Parcelid]         INT             IDENTITY (1, 1) NOT NULL,
    [Senderid]         BIGINT          NULL,
    [Receiverid]       BIGINT          NULL,
    [Collectioncenterid ]  INT             NULL,
    [Parceltypeid]     INT             NULL,
    [Parcelweight]     DECIMAL (10, 2) NULL,
    [Dimensions]       VARCHAR (50)    NULL,
    [Parcelstatusid]   INT             NULL,
    [Transitdays]      INT             NULL,
    [Deliveryfee]      DECIMAL (10, 2) NULL,
    [Trackingnumber]   VARCHAR (50)    NULL,
    [Pickupdate]       DATETIME        NULL,
    [Dropoffdate]      DATETIME        NULL,
    [Createddate]      DATETIME        DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([Parcelid] ASC),
    FOREIGN KEY ([Collectioncenterid]) REFERENCES [dbo].[Parcelcollectioncenters] ([Collectioncenterid]),
    FOREIGN KEY ([Parcelstatusid]) REFERENCES [dbo].[Parcelstatus] ([Parcelstatusid]),
    FOREIGN KEY ([Parcelstatusid]) REFERENCES [dbo].[Parcelstatus] ([Parcelstatusid]),
    FOREIGN KEY ([Parceltypeid]) REFERENCES [dbo].[Parceltypes] ([Parceltypeid]),
    FOREIGN KEY ([Parceltypeid]) REFERENCES [dbo].[Parceltypes] ([Parceltypeid]),
    FOREIGN KEY ([Parceltypeid]) REFERENCES [dbo].[Parceltypes] ([Parceltypeid]),
    FOREIGN KEY ([Receiverid]) REFERENCES [dbo].[Systemstaffs] ([Userid]),
    FOREIGN KEY ([Receiverid]) REFERENCES [dbo].[Systemstaffs] ([Userid]),
    FOREIGN KEY ([Receiverid]) REFERENCES [dbo].[Systemstaffs] ([Userid]),
    FOREIGN KEY ([Senderid]) REFERENCES [dbo].[Systemstaffs] ([Userid]),
    FOREIGN KEY ([Senderid]) REFERENCES [dbo].[Systemstaffs] ([Userid]),
    FOREIGN KEY ([Senderid]) REFERENCES [dbo].[Systemstaffs] ([Userid]),
    UNIQUE NONCLUSTERED ([Trackingnumber] ASC)
);