CREATE TABLE [dbo].[Propertyhouselisting] (
    [Houselistingid] INT             IDENTITY (1, 1) NOT NULL,
    [Title]          VARCHAR (200)   NOT NULL,
    [Price]          DECIMAL (10, 2) NOT NULL,
    [Locations]      VARCHAR (400)   NOT NULL,
    [Isforrent]      BIT             NOT NULL,
    [Bedrooms]       INT             NOT NULL,
    [Bathrooms]      INT             NOT NULL,
    [Descriptions]   VARCHAR (2000)  NOT NULL,
    [Contacts]       VARCHAR (200)   NOT NULL,
    [Extra]          VARCHAR (200)   NULL,
    [Extra1]         VARCHAR (200)   NULL,
    [Extra2]         VARCHAR (200)   NULL,
    [Extra3]         VARCHAR (200)   NULL,
    [Extra4]         VARCHAR (200)   NULL,
    [Extra5]         VARCHAR (200)   NULL,
    [Extra6]         VARCHAR (200)   NULL,
    [Extra7]         VARCHAR (200)   NULL,
    [Extra8]         VARCHAR (200)   NULL,
    [Extra9]         VARCHAR (200)   NULL,
    [Extra10]        VARCHAR (200)   NULL,
    [Isactive]       BIT             DEFAULT ((1)) NOT NULL,
    [Isdeleted]      BIT             DEFAULT ((0)) NOT NULL,
    [Createdby]      BIGINT          NOT NULL,
    [Modifiedby]     BIGINT          NOT NULL,
    [Datecreated]    DATETIME        NOT NULL,
    [Datemodified]   DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([Houselistingid] ASC)
);

