CREATE TABLE [dbo].[Systemstaffs] (
    [Userid]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [Firstname]           VARCHAR (70)  NOT NULL,
    [Lastname]            VARCHAR (70)  NOT NULL,
    [Phonenumber]         VARCHAR (15)  NOT NULL,
    [Username]            VARCHAR (100) NOT NULL,
    [Emailaddress]        VARCHAR (100) NOT NULL,
    [Genderid]            BIGINT        DEFAULT ((0)) NOT NULL,
    [Maritalstatusid]     BIGINT        DEFAULT ((0)) NOT NULL,
    [Roleid]              BIGINT        NOT NULL,
    [Passharsh]           VARCHAR (100) NOT NULL,
    [Passwords]           VARCHAR (100) NOT NULL,
    [Isactive]            BIT           NOT NULL,
    [Isdeleted]           BIT           CONSTRAINT [DF__Systemsta__Isdel__3D5E1FD2] DEFAULT ((0)) NOT NULL,
    [Isdefault]           BIT           CONSTRAINT [DF__Systemsta__Isdef__3E52440B] DEFAULT ((0)) NOT NULL,
    [Loginstatus]         INT           CONSTRAINT [DF__Systemsta__Login__3F466844] DEFAULT ((2)) NOT NULL,
    [Passwordresetdate]   DATETIME      NOT NULL,
    [Parentid]            BIGINT        CONSTRAINT [DF__Systemsta__Paren__403A8C7D] DEFAULT ((0)) NOT NULL,
    [Userprofileimageurl] VARCHAR (255) NULL,
    [Usercurriculumvitae] VARCHAR (255) NULL,
    [Idnumber]            INT           NULL,
    [Updateprofile]       BIT           DEFAULT ((1)) NOT NULL,
    [Extra]               VARCHAR (100) NULL,
    [Extra1]              VARCHAR (100) NULL,
    [Extra2]              VARCHAR (100) NULL,
    [Extra3]              VARCHAR (100) NULL,
    [Extra4]              VARCHAR (100) NULL,
    [Extra5]              VARCHAR (100) NULL,
    [Createdby]           BIGINT        NOT NULL,
    [Modifiedby]          BIGINT        NOT NULL,
    [Lastlogin]           DATETIME      NOT NULL,
    [Datemodified]        DATETIME      NOT NULL,
    [Datecreated]         DATETIME      NOT NULL,
    CONSTRAINT [PK__Systemst__1797D0244E632A92] PRIMARY KEY CLUSTERED ([Userid] ASC),
    CONSTRAINT [FK__Systemsta__Rolei__412EB0B6] FOREIGN KEY ([Roleid]) REFERENCES [dbo].[Systemroles] ([Roleid])
);

